# [build]
# target = "x86_64-unknown-linux-gnu"

[target.armv7-linux-androideabi]
ar = "/home/gihexdev00/Android/Sdk/ndk/26.2.11394342/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
linker = "/home/gihexdev00/Android/Sdk/ndk/26.2.11394342/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi34-clang"
[target.aarch64-linux-android]
ar = "/home/gihexdev00/Android/Sdk/ndk/26.2.11394342/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
linker = "/home/gihexdev00/Android/Sdk/ndk/26.2.11394342/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang"
[target.i686-linux-android]
ar = "/home/gihexdev00/Android/Sdk/ndk/26.2.11394342/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
linker = "/home/gihexdev00/Android/Sdk/ndk/26.2.11394342/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android34-clang"
[target.x86_64-linux-android]
ar = "/home/gihexdev00/Android/Sdk/ndk/26.2.11394342/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
linker = "/home/gihexdev00/Android/Sdk/ndk/26.2.11394342/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android34-clang"